# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def tx_im
   pod 'TXIMSDK_iOS', '4.9.1'
end

def common_pods_all
  pod 'SDWebImage', '= 5.12.1'
  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'CWStatusBarNotification', '~> 2.3.5'
  pod 'WMPageController', '~> 2.4.0'
end

def player_pods(subName)
  pod 'SuperPlayer', :path => './TXLiteAVDemo/SuperPlayerKit/SuperPlayer.podspec', :subspecs => ["#{subName}"]
end

def tx_UGCKit(subName)
  pod 'UGCKit', :path => './TXLiteAVDemo/UGCKit/UGCKit.podspec', :subspecs => ["#{subName}"]
end

def beauty_pods
  pod 'BeautySettingKit', :path => './TXLiteAVDemo/BeautySettingKit/BeautySettingKit.podspec'
end



target 'TXLiteAVDemo_Professional' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXLiteAVDemo_Professional
  common_pods_all
  player_pods 'Professional'
  tx_im
  tx_UGCKit 'Professional'
  beauty_pods
end

target 'TXReplaykitUpload_Professional' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for TXReplaykitUpload_Professional

end

